# Generated by Django 4.2.2 on 2023-06-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
