# Generated by Django 4.2.2 on 2023-06-29 17:35

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_delete_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='web.employee', verbose_name='Руководитель'),
        ),
    ]
