# Generated by Django 4.2.2 on 2023-06-29 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_employee_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='parent',
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='web.employee'),
        ),
    ]
