# Generated by Django 4.2.2 on 2023-06-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_role_worker_remove_genre_parent_delete_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_level',
            field=models.IntegerField(default=1),
        ),
    ]
