# Generated by Django 4.2.2 on 2023-06-29 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_rename_manager_worker_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='hire_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
